config/routes.rb
Rails.application.routes.draw do
  resources :birthday_cards
  root 'birthday_cards#index'
end

app/models/birthday_card.rb
class BirthdayCard < ActiveRecord::Base
  validates :title, presence: true
  validates :greeting, presence: true
  validates :author, presence: true
  has_attached_file :image,
    styles: { medium: "300x300>", thumb: "100x100>" },
    default_style: :medium
  validates_attachment :image, presence: true,
    content_type: { content_type: /\Aimage/ },
    file_name: { matches: [/png\Z/, /jpe?g\Z/, /gif\Z/] },
    size: { in: 0..5.megabytes }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/birthday_cards_controller.rb
class BirthdayCardsController < ApplicationController
  before_action :set_birthday_card, only: [:show, :edit, :update, :destroy]

  # GET /birthday_cards
  # GET /birthday_cards.json
  def index 
    @birthday_cards = BirthdayCard.order(:created_at).reverse_order.page(params[:page])
  end

  # GET /birthday_cards/1
  # GET /birthday_cards/1.json
  def show
  end

  # GET /birthday_cards/new
  def new
    @birthday_card = BirthdayCard.new
  end

  # # GET /birthday_cards/1/edit
  def edit
  end

  # POST /birthday_cards
  # POST /birthday_cards.json
  def create
    @birthday_card = BirthdayCard.new(birthday_card_params)

    respond_to do |format|
      if @birthday_card.save
        format.html { redirect_to @birthday_card, notice: 'Birthday card was successfully created.' }
        format.json { render :show, status: :created, location: @birthday_card }
      else
        format.html { render :new }
        format.json { render json: @birthday_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /birthday_cards/1
  # PATCH/PUT /birthday_cards/1.json
  def update
    respond_to do |format|
      if @birthday_card.update(birthday_card_params)
        format.html { redirect_to @birthday_card, notice: 'Birthday card was successfully updated.' }
        format.json { render :show, status: :ok, location: @birthday_card }
      else
        format.html { render :edit }
        format.json { render json: @birthday_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birthday_cards/1
  # DELETE /birthday_cards/1.json
  def destroy
    @birthday_card.destroy
    respond_to do |format|
      format.html { redirect_to birthday_cards_url, notice: 'Birthday card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_birthday_card
      @birthday_card = BirthdayCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def birthday_card_params
      params.require(:birthday_card).permit(:image, :title, :greeting, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birthday_cards_helper.rb
module BirthdayCardsHelper
end

app/views/birthday_cards/_card.html.haml
.row
  .col-md-6
    %a{ href: birthday_card.image.url(:original) }
      = image_tag birthday_card.image.url(:medium), class: 'img-rounded img-responsive'
  .col-md-6
    .text-center
      %a{ href: birthday_card_path(birthday_card) }
        %h4.multiline= birthday_card.title
    %p
      = simple_format birthday_card.greeting
    %p.text-right.multiline
      %em Yours
      %strong
        = birthday_card.author
%br

app/views/birthday_cards/_form.html.haml
.row
  .col-md-11.col-md-offset-1
    = bootstrap_form_for(@birthday_card) do |f|
      - if @birthday_card.errors.any?
        .alert.alert-danger
          %h3.header
            = pluralize(@birthday_card.errors.count, "error")
            prohibited this Birthday card from being saved:
          %ul
            - @birthday_card.errors.full_messages.each do |message|
              %li= message
      .form-group
        = f.file_field :image
        - if @birthday_card.id
          =image_tag @birthday_card.image.url(:thumb), class: 'img-rounded img-responsive'
      .form-group
        = f.text_field :title
      .form-group
        = f.text_area :greeting, rows: 5
      .form-group
        = f.text_field :author
      .actions
        = f.submit "Submit Birthday card", class: 'btn btn-success', id: 'file_selection'

app/views/birthday_cards/edit.html.haml
.container
  .row
    %h1.text-center.header Editing Birthday Card
  .row
    .col-md-8.col-md-offset-2
      .well
        = render 'form'
        .row
          .col-md-12.text-center
            .btn-group{ role: 'group', 'aria-label' => 'true' }
              = link_to 'To Birthday card', @birthday_card, class: 'btn btn-primary'
              = link_to 'To all Birthday cards', birthday_cards_path, class: 'btn btn-info'

app/views/birthday_cards/index.html.haml
.container
  -if @birthday_cards.length != 0
    .row
      .col-md-12
        %h1.text-center.header Your Birthday Cards
    .row
      .col-md-12.text-center
        = paginate @birthday_cards
    .row
    - @birthday_cards.each do |birthday_card|
      .col-md-6
        .well
          = render partial: 'birthday_cards/card', locals: { birthday_card: birthday_card }
          .row
            .col-md-12.text-center
              .btn-group{ role: 'group' }
                = link_to 'Show', birthday_card, class: 'btn btn-primary'
                = link_to 'Edit', edit_birthday_card_path(birthday_card), class: 'btn btn-warning'
                = link_to 'Delete', birthday_card, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
  -else
    .row
      .col-md-12.text-center
        %h1.header Be the first to greet Elizabeth!
    .row
      .col-md-12.text-center
        = link_to 'Make the first Birthday card!', new_birthday_card_path, class: 'btn btn-success btn-lg'

app/views/birthday_cards/new.html.haml
.container
  .row
    %h1.text-center.header New Birthday Card
  .row
    .col-md-8.col-md-offset-2
      .well
        = render 'form'
        .row
          .col-md-12.text-center
            .btn-group{ role: 'group' }
              = link_to 'To all Birthday cards', birthday_cards_path, class: 'btn btn-info'

app/views/birthday_cards/show.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      .well
        = render partial: 'birthday_cards/card', locals: { birthday_card: @birthday_card }
        .row
          .col-md-12.text-center
            .btn-group{ role: 'group' }
              = link_to 'All', birthday_cards_path, class: 'btn btn-primary'
              = link_to 'Edit', edit_birthday_card_path(@birthday_card), class: 'btn btn-warning'
              = link_to 'Delete', @birthday_card, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      = link_to 'Happy Bday Liz!', root_path, class: 'navbar-brand'
      %button.navbar-toggle.collapsed{'data-toggle' => "collapse", 'data-target' => '#header_menu', 'aria-expanded' => 'false'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .collapse.navbar-collapse#header_menu
      = link_to 'New Birthday card', new_birthday_card_path, class: 'btn btn-success navbar-btn'
      = link_to 'GitHub', "https://github.com/DTLuna/liz_bday", class: 'btn btn-info navbar-btn navbar-right' 

app/views/layouts/_messages.html.haml
-if notice
  .alert.alert-info
    = notice
    %a.text-right#close{ href: '#', 'data-dismiss' => "alert" }×

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=' }
    %title Liz B-day
    = favicon_link_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    = yield